services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'