services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    extra_hosts:
      - 'host.docker.internal:host-gateway'